# SPDX-License-Identifier: MPL-2.0
# mise toolchain pins — mirrors .tool-versions (asdf) for mise users.
# Only the toolchains this repo actually builds with; keep pinned, not "latest".

[tools]
elixir = "1.16.0"
erlang = "26.2.1"
